title: Travel With Camera
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0
  brandStrength: 0
  rhythmicContrast: 0
  brandColors:
    - '#FFFFFF'
    - '#051526'
    - '#928181'
    - '#384C64'
    - '#A1ADB8'
  lightness: 0
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
name: Travel With Camera
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.5332975
layout_spectrum: 0.9479054
