title: Travel With Camera
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
color:
  saturation: 0.4957035
  brandStrength: 0.5075188
  lightness: 0.4989259
  brandColors:
    - '#E9E9E9'
    - '#00D2FF'
    - '#E1E5E7'
    - '#D5E7EB'
    - '#50D9F7'
  rhythmicContrast: 0.4978518
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
name: Travel With Camera
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.5805585
layout_spectrum: 0.2755102
