typography_spectrum: 0.5332975
color:
  saturation: 0
  brandStrength: 0
  rhythmicContrast: 0
  brandColors:
    - '#FFFFFF'
    - '#051526'
    - '#928181'
    - '#384C64'
    - '#A1ADB8'
  lightness: 0
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.6493018
analytics:
  twitter: null
  google: null
  facebook: null
name: Travel With Camera
cta:
  bucket: null
  version: null
  domain: null
navigation:
  - name: '#travelwithme'
    url: 'http://vyte.in/travel'
    type: external
favicon: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: ''
purpose: []
